### ISSUE TITLE
systemDirectory 변경

### ISSUE THREAD

**Issue by pushwing** [codeigniter-kr/ci4userguidekr#12]
http://ci4doc.cikorea.net/installation/installing_composer.html#codeigniter4

app/Config/Paths.php 를 아래와 같이 수정하라고 되어 있으나 ROOTPATRH는 선언 전이라 작동되지 않음.

$systemDirectory = ROOTPATH . '/vendor/codeigniter4/framework/system';

아래와 같이 수정해야 정상작동함
public $systemDirectory =  '../vendor/codeigniter4/framework/system';

**Comment by Terrorboy** [comment]
https://github.com/codeigniter-kr/ci4userguidekr/pull/14 에서 변경 적용되었습니다.
> 프레임워크 소스 기반으로 변경했습니다.
![image](https://user-images.githubusercontent.com/5427199/98117610-5fe72b80-1eed-11eb-9094-44fe3c24bd63.png)


## 변경내용
```
$systemDirectory = ROOTPATH . '/vendor/codeigniter4/framework/system';
```
to
```
public $systemDirectory = __DIR__ . '/../../vendor/codeigniter4/framework/system';
```

**Comment by Terrorboy** [comment]
최신 버전 매뉴얼에는 삭제된 부분으로 추후 어떻게 할지 논의해야 할 듯합니다.
