### ISSUE TITLE
readme.md 수정 요청

### ISSUE THREAD

**Issue by pushwing** [codeigniter-kr/ci4userguidekr#8]
저장소가 ci4userguidekr 이긴 하지만 타이틀에 명시를 해주면 좋을 것 같습니다.

CodeIgniter 한국어 사용자 가이드 -> CodeIgniter4 한국어 사용자 가이드

**Comment by Terrorboy** [comment]
https://github.com/codeigniter-kr/ci4userguidekr/issues/8 에서 반영되었습니다.

감사합니다.
